# Generated by Django 2.2.4 on 2019-08-11 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workex', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=256)),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workex', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=256)),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
