# Generated by Django 2.2.4 on 2019-08-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='isSold',
            new_name='is_sold',
        ),
    ]
