# Generated by Django 2.2.4 on 2019-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190811_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
