# Generated by Django 2.2.4 on 2019-08-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_story_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ProducerProfile'),
        ),
    ]
