# Generated by Django 2.2.4 on 2019-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190815_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='stories',
            field=models.ManyToManyField(related_name='genres', to='main.Story'),
        ),
    ]
