# Generated by Django 2.2.4 on 2019-08-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190815_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[(1, 'dystopia'), (2, 'scifi'), (3, 'romance'), (4, 'fantasy'), (5, 'horror')], max_length=256),
        ),
    ]
