# Generated by Django 2.2.4 on 2019-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190815_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('dys', 'dystopia'), ('sci', 'scifi'), ('rom', 'romance'), ('fant', 'fantasy'), ('hor', 'horror')], max_length=256),
        ),
    ]
