# Generated by Django 2.2.4 on 2019-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190815_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='stories',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='fantasy', max_length=256),
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.ManyToManyField(to='main.Genre'),
        ),
    ]
