# Generated by Django 2.2.4 on 2019-08-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='story',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Story'),
        ),
    ]
