# Generated by Django 2.2.4 on 2019-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_featured_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='upload',
            new_name='upload_vid',
        ),
        migrations.AddField(
            model_name='featured',
            name='upload_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_img/'),
        ),
    ]
