# Generated by Django 2.2.4 on 2019-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190815_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerprofile',
            name='photo',
            field=models.ImageField(blank=True, default='/static/auth/def_dp.jpg', null=True, upload_to='upload_dp/'),
        ),
    ]
